name: Backporter
on: [issue_comment, workflow_dispatch]

jobs:
  issue_commented:
    name: Issue comment
    runs-on: ubuntu-latest
    steps:
    - name: echo-out
      run: echo '${{ toJSON(github.event) }}'
