name: Issue comment handler
on: [issue_comment, workflow_dispatch]

jobs:
  issue_commented:
    if: $COMMENT == 'test'
    name: Issue comment
    runs-on: ubuntu-latest
    steps:
    - name: echo-out
      run: echo '${{ toJSON(github.event) }}'
    env:
      COMMENT: ${{ github.event.comment.body }}
