name: Backporter
on: [issue_comment]

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: contains(${{ github.event.issue.comment }}, '/backport')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: echo-out
      run: echo It is a backport!
#     env: 
#       EVENT: ${{ github.event.issue }}
