name: Backporter
on: [issue_comment, workflow_dispatch]

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: contains($ISSUE, '/backport')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: echo-out
      run: echo It is a backport!
    env: 
      ISSUE: ${{ github.event.issue }}
# 
