name: Backporter
on: [issue_comment]

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: contains(env.COMMENT, '/backport')
    runs-on: ubuntu-latest
    steps:
    - run: echo The comment is "$COMMENT" 
    env:
      COMMENT: ${{ github.event.issue.comment }}
      
