name: Backporter
on: [issue_comment]

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: contains(${{ github.event.issue.comment }}, '/backport')
    runs-on: ubuntu-latest
    steps:
    - run: |
          echo The comment is "$COMMENT"
          echo "$EVENT"
      env: 
        COMMENT: ${{ github.event.issue.comment }}
        EVENT: ${{ github.event }}
#     env:
#       COMMENT: ${{ github.event.issue.comment }}
      
